### ISSUE TITLE
Monthly List Doesn't Update Anymore

### ISSUE THREAD

**Issue by RhysLindmark** [ssono/monthly-listentothis-playlist#1]
Hey hey!

First off, THANK YOU so much for this list. I love it and have been using it for as long as I can remember.

There's an issue though: the Latest Top 50 list doesn't update anymore. See https://open.spotify.com/playlist/0SZt1HRceSHEOd17VxbPSj?si=i6KrpBBtTcG0-gv0njJUqA

Perhaps something changed with the Spotify API?

Let me know if I can help and thanks again!

**Comment by RhysLindmark** [comment]
Wanted to mention @ssono to make sure you saw it just in case. :)

**Comment by ssono** [comment]
Hi @RhysLindmark . Thank you! I made a mistake with an edge case in the search. Fixed and re-ran it.
